version: '3'
services:
  pg:
    image: postgres
    container_name: "bili_videos_postgres"
    ports:
      - "10123:5432"  # 暴露端口 可以本地连接查看数据
    volumes:
      - .data/pg:/var/lib/postgresql  # 数据持久化至本地
    environment:
      - POSTGRES_DB=videos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

  redis:
    image: redis
    container_name: "bili_videos_redis"
    volumes:
      - .data/redis:/var/lib/redis  # 数据持久化至本地

  web:
    container_name: "bili_videos_go"
    build: .
    links:
      - pg
      - redis
    depends_on:
      - pg
      - redis

#volumes:
#  pg_data: {}
#  redis_data: {}